### ISSUE TITLE
5.5代码再次运行出错问题

### ISSUE THREAD

**Issue by Carl-Lei** [caicloud/tensorflow-tutorial#103]
在5.5的代码中，我第一次运行的时候，结果是对的。当我再次运行该程序的时候，出现错误： Variable layer1/weights/ExponentialMovingAverage/ already exists, disallowed.
错误的地方是这一行程序： variables_averages_op = variable_averages.apply(tf.trainable_variables())
我对inference中做了如下修改后，仍然提示这样的错误，请问该怎么解决？

def inference(input_tensor, regularizer,reuse=False):

    with tf.variable_scope('layer1',reuse=reuse):

        weights = get_weight_variable([INPUT_NODE, LAYER1_NODE], regularizer)
        biases = tf.get_variable("biases", [LAYER1_NODE], initializer=tf.constant_initializer(0.0))
        layer1 = tf.nn.relu(tf.matmul(input_tensor, weights) + biases)
        print(weights)

    with tf.variable_scope('layer2',reuse=reuse):
        weights = get_weight_variable([LAYER1_NODE, OUTPUT_NODE], regularizer)
        biases = tf.get_variable("biases", [OUTPUT_NODE], initializer=tf.constant_initializer(0.0))
        layer2 = tf.matmul(layer1, weights) + biases
        print(weights)
    return layer2

在第一次运行时，train里的y = inference(x, regularizer,reuse=False)
第二次运行时，train里的y = inference(x, regularizer,reuse=True)

**Comment by Carl-Lei** [comment]
有人遇到类似的问题吗？有哪位知道怎么解决吗？

**Comment by hurae** [comment]
首次执行时，没有错误，当再次执行时，会出现如下错误：

ValueError: Variable layer1-conv1/weight already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope? Originally defined at:

如果Restart kernel 之后再次执行就不会有问题了（相当于重启了spyder，这样不能从根本解决问题。而且多次重启，也不太好。）

这个问题主要是由于再次执行的时候，之前的计算图已经存在了，再次执行时会和之前已经存在的产生冲突。解决方法： 
1.在代码前面加一句：tf.reset_default_graph（）
--------------------- 
作者：xytywh 
来源：CSDN 
原文：https://blog.csdn.net/xiaohuihui1994/article/details/80829832 
版权声明：本文为博主原创文章，转载请附上博文链接！
