### ISSUE TITLE
第二版书中5.2.1节，100页处，train_step后面的部分没有缩进，这部分应该是属于train函数的吧

### ISSUE THREAD

**Issue by Torero2016** [caicloud/tensorflow-tutorial#108]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind feature

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by skx300** [comment]
是的，是输入train函数的。

**Comment by beiyan1911** [comment]
第二版100页前后代码缩进有问题，运行之后结果也和书中的差别很大
