### ISSUE TITLE
8.4节的循环神经网络的sin正弦曲线案例不合适

### ISSUE THREAD

**Issue by liuyaqiu** [caicloud/tensorflow-tutorial#109]
**8.4节的循环神经网络的sin正弦曲线案例不合适**:

**1** 书中给出的并非一个序列问题，按照书中给定的数据格式，LSTM的输入是X: (None, 1, 10), X的shape的形式按照tf.nn.dynamic_rnn的API解释是(batch_size, max_time, ...)，这里max_time为1，显然序列长度变成了1．
**2** 即使把LSTM的输入形式修正为(None, 10, 1)，这个例子仍然非常不合适，因为当step_gap(例子中给的是0.01)取的很小的时候，序列中的10个值会非常接近，最后的输出值与输入序列的最后一个值非常接近。这种情况下反而直接用Dense Network建模会取得非常好的效果(y约等于x[-1])。实际测试使用Dense Network直接求解速度更快，而且准确度更高。

**Comment by haithink** [comment]
> **8.4节的循环神经网络的sin正弦曲线案例不合适**:
> 
> **1** 书中给出的并非一个序列问题，按照书中给定的数据格式，LSTM的输入是X: (None, 1, 10), X的shape的形式按照tf.nn.dynamic_rnn的API解释是(batch_size, max_time, ...)，这里max_time为1，显然序列长度变成了1．
> **2** 即使把LSTM的输入形式修正为(None, 10, 1)，这个例子仍然非常不合适，因为当step_gap(例子中给的是0.01)取的很小的时候，序列中的10个值会非常接近，最后的输出值与输入序列的最后一个值非常接近。这种情况下反而直接用Dense Network建模会取得非常好的效果(y约等于x[-1])。实际测试使用Dense Network直接求解速度更快，而且准确度更高。

请问Dense Network建模的例子有没?参考下。

**Comment by liuyaqiu** [comment]
```python
def dense_model(X, y, is_training):
    output = tf.contrib.layers.fully_connected(X, 1, activation_fn=None)
    predictions = tf.contrib.layers.flatten(output)
    if not is_training:
        return predictions, None, None
    
    loss = tf.losses.mean_squared_error(labels=y, predictions=predictions)
    train_op = tf.contrib.layers.optimize_loss(
        loss, tf.train.get_global_step(),
        optimizer="Adagrad", learning_rate=0.1)
    return predictions, loss, train_op
```
这是只有一层输出层的dense_model，且该层是线性层。将后续代码中的`lstm_model`均替换为`dense_model`即可。
从运行结果来看dense_model的准确性非常高，因为输出y的值起始取为输入X的序列值的最后一项即可达到这种精度。
