### ISSUE TITLE
第六章6.4.1 inference代码有误

### ISSUE THREAD

**Issue by ShusenTang** [caicloud/tensorflow-tutorial#113]
**BUG REPORT**:

Deep_Learning_with_TensorFlow/1.4.0/Chapter06/LeNet-5/LeNet5_infernece.py中第42行
应该改成reshaped = tf.reshape(pool2, [-1, nodes])，否则进行运行eval.py进行测试时会报错Failed to convert object of type <class 'list'> to Tensor.

**Comment by tankle** [comment]
我也遇到了这个问题，请问有解决嘛？

**Comment by ShusenTang** [comment]
我写了解决方案啊，把LeNet5_infernece.py中第42行改成reshaped = tf.reshape(pool2, [-1, nodes])

**Comment by haithink** [comment]
主要是 输入 x 的 batch_size 这个维度填 None 的话就会有 这个问题
