### ISSUE TITLE
第6章处理花图片数据的函数中打乱训练图片和标签问题

### ISSUE THREAD

**Issue by CrucibleV** [caicloud/tensorflow-tutorial#114]
#将训练数据随机打乱以获得更好的训练效果
state = np.random.get_state()
 np.random.shuffle(training_images)
 np.random.set_state(state)
 np.random.shuffle(training_labels)

在这里training_images和training_labels不是一一对应的关系吗？？那么这俩分别单独shuffle打乱顺序，那么不久全错位了吗？？是怎么回事啊？？

**Comment by Rmuli** [comment]
np.random.set_state(state)，就是保持两者的顺序一直啊
