### ISSUE TITLE
第六章6.5.2迁移学习代码的问题

### ISSUE THREAD

**Issue by zchfaq** [caicloud/tensorflow-tutorial#135]
代码中定义了一个变量trainable_variables，来获取需要训练的变量，但是后续代码中完全没有使用它

后面的注释里面说“只会更新指定的部分参数”，但是按照之前的代码逻辑应该是更新了全部的参数的

请修复这个bug

**Comment by zhangxiangchn** [comment]
我也遇到了同样的问题？请问您后来解决了吗？

**Comment by zhangxiangchn** [comment]
> 代码中定义了一个变量trainable_variables，来获取需要训练的变量，但是后续代码中完全没有使用它
> 
> 后面的注释里面说“只会更新指定的部分参数”，但是按照之前的代码逻辑应该是更新了全部的参数的
> 
> 请修复这个bug

我也遇到了同样的问题？请问您后来解决了吗？

**Comment by niunuinui** [comment]
是不是下面的
`train_step = tf.train.RMSPropOptimizer(LEARNING_RATE).minimize(tf.losses.get_total_loss())`

应该改成
`train_step = tf.train.RMSPropOptimizer(LEARNING_RATE).minimize(tf.losses.get_total_loss(), var_list=trainable_variables)`
