### ISSUE TITLE
按书上路径安装docker TF 0.12.0版本，juypter需要密码才能打开。

### ISSUE THREAD

**Issue by dashjim** [caicloud/tensorflow-tutorial#15]
如果不宜公开密码请发至7303594@qq.com。谢谢

**Comment by perhapszzy** [comment]
这个密码在docker运行的时候会给出。你可以先通过docker ps查看运行的docker id，然后通过docker log来查看juypter的密码。

**Comment by dashjim** [comment]
Many thanks.
