### ISSUE TITLE
无法用下载 caicloud 的 tensorflow docker 镜像

### ISSUE THREAD

**Issue by cjd9023** [caicloud/tensorflow-tutorial#19]
无法用docker pull cargo.caicloud.io/tensorflow/tensorflow:0.12.0
docker: Error response from daemon: Get https://cargo.caicloud.io/v1/_ping: dial tcp: lookup cargo.caicloud.io on 210.22.70.3:53: server misbehaving

**Comment by perhapszzy** [comment]
我是可以的啊。。可能是网络问题，你再试一试？
