### ISSUE TITLE
第六章迁移学习怎么读取png图片

### ISSUE THREAD

**Issue by giser-yugang** [caicloud/tensorflow-tutorial#25]
我使用加载的inception-v3模型去计算图片的特征向量，图片是jpg格式的没问题，但是是png格式的就会出错，采用
`image_data = gfile.FastGFile(image_path, 'rb').read()`
去读取png图片会在
`bottleneck_values = sess.run(bottleneck_tensor, {image_data_tensor: image_data})`

处计算特征向量时出错，控制台错误如下：
```
......
Not a JPEG file: starts with 0x89 0x50
......
InvalidArgumentError (see above for traceback): Invalid JPEG data, size 19839
     [[Node: import/DecodeJpeg = DecodeJpeg[acceptable_fraction=1, channels=3, dct_method="", fancy_upscaling=true, ratio=1, try_recover_truncated=false, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_import/DecodeJpeg/contents_0)]]
```
我猜测应该是那句读取图片的代码只支持jpg类型，但是我该怎么修改使其支持png格式？

**Comment by perhapszzy** [comment]
你需要先将png格式的图片转化为jpg格式再传进去

**Comment by lxtGH** [comment]
必须转换成jpg 才行
