### ISSUE TITLE
能给一下tensorflow 1.1.0对应的程序吗？

### ISSUE THREAD

**Issue by SunYiLun** [caicloud/tensorflow-tutorial#46]

**Comment by lienhua34** [comment]
@SunYiLun 你好，你是指 Deep_Learning_with_TensorFlow 目录下的样例程序代码吗？

**Comment by SunYiLun** [comment]
是的，因为之前运行第八章的LSTM语言模型会报错，tensorflow版本是1.1.0，用的代码是您github上1.0.0d的，不过目前已经把错误解决，谢谢您的及时回复

**Comment by ScorpioCPH** [comment]
@SunYiLun 感谢反馈，我们后面会有计划，更新这些示例代码，以便于在新版本上可以运行

**Comment by lilallen** [comment]
lstm预测正弦函数在1.2.0上报错，期待给出新版本代码
