### ISSUE TITLE
请问在tensorflow里面怎样定义自己的激活函数？

### ISSUE THREAD

**Issue by xuanjihe** [caicloud/tensorflow-tutorial#47]
最近遇到一个问题，不知道怎么在tensorflow里面自定义自己的激活函数，比如（log），在tensorflow里面的反向求导机制是怎样的，是框架自动求导还是要自己预先写好求导文件，然后再一层一层连接起来？求大神指导，谢谢！

**Comment by perhapszzy** [comment]
tensorflow会自动求导的
