### ISSUE TITLE
使用TensorFlow实现手写数字识别显示raise IOError, 'Not a gzipped file'

### ISSUE THREAD

**Issue by SunsetWan** [caicloud/tensorflow-tutorial#48]
1.git clone https://github.com/martin-gorner/tensorflow-mnist-tutorial.git 下载手写数字识别和下载依赖的训练数据的代码
2.运行手写数字训练示例    
      python mnist_1.0_softmax.py
![test1](https://user-images.githubusercontent.com/16316111/27324074-861f153a-55d6-11e7-8d93-056e81b7f607.png)

经过对关键词的google之后，我似乎找到解决方法，如下:
![answer](https://user-images.githubusercontent.com/16316111/27324235-1ea48614-55d7-11e7-9565-9b518fbdf09b.png)
我于是照做，下载了这四个文件。
    但是我并不知道把这四个文件放在哪里，该解决方法也未说明。
    我尝试把这四个文件直接放在git clone过来的文件夹中，继续执行语句python mnist_1.0_softmax.py
    仍然重复如上错误。
    请问，这四个数据文件应该放在哪里呢？

**Comment by lienhua34** [comment]
@SunsetWan 你直接使用 TensorFlow 官方的 MNIST 样例代码即可 https://github.com/tensorflow/tensorflow/tree/r1.1/tensorflow/examples/tutorials/mnist
