### ISSUE TITLE
第九章中 监控可视化代码运行报错。版本1.2.0

### ISSUE THREAD

**Issue by chnhaoqiu** [caicloud/tensorflow-tutorial#52]
Extracting /MNIST_data\train-images-idx3-ubyte.gz
Extracting /MNIST_data\train-labels-idx1-ubyte.gz
Extracting /MNIST_data\t10k-images-idx3-ubyte.gz
Extracting /MNIST_data\t10k-labels-idx1-ubyte.gz
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-12-2436fc2ab63a> in <module>()
      1 if __name__ == '__main__':
----> 2     main()

<ipython-input-11-a17be7934905> in main()
     18 
     19     with tf.name_scope('train'):
---> 20         train_step = tf.train.AdamOptimizer(0.001).minimize(cross_entropy)
     21 
     22     with tf.name_scope('accuracy'):

D:\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\training\optimizer.py in minimize(self, loss, global_step, var_list, gate_gradients, aggregation_method, colocate_gradients_with_ops, name, grad_loss)
    320           "No gradients provided for any variable, check your graph for ops"
    321           " that do not support gradients, between variables %s and loss %s." %
--> 322           ([str(v) for _, v in grads_and_vars], loss))
    323 
    324     return self.apply_gradients(grads_and_vars, global_step=global_step,

ValueError: No gradients provided for any variable, check your graph for ops that do not support gradients, between variables ["<tf.Variable 'layer1/weights/Variable:0' shape=(784, 500) dtype=float32_ref>", "<tf.Variable 'layer1/biases/Variable:0' shape=(500,) dtype=float32_ref>", "<tf.Variable 'layer2/weights/Variable:0' shape=(500, 10) dtype=float32_ref>", "<tf.Variable 'layer2/biases/Variable:0' shape=(10,) dtype=float32_ref>", "<tf.Variable 'layer1_1/weights/Variable:0' shape=(784, 500) dtype=float32_ref>", "<tf.Variable 'layer1_1/biases/Variable:0' shape=(500,) dtype=float32_ref>", "<tf.Variable 'layer2_1/weights/Variable:0' shape=(500, 10) dtype=float32_ref>", "<tf.Variable 'layer2_1/biases/Variable:0' shape=(10,) dtype=float32_ref>", "<tf.Variable 'layer1_2/weights/Variable:0' shape=(784, 500) dtype=float32_ref>", "<tf.Variable 'layer1_2/biases/Variable:0' shape=(500,) dtype=float32_ref>", "<tf.Variable 'layer2_2/weights/Variable:0' shape=(500, 10) dtype=float32_ref>", "<tf.Variable 'layer2_2/biases/Variable:0' shape=(10,) dtype=float32_ref>"] and loss Tensor("cross_entropy_2/Mean:0", shape=(), dtype=float32).

**Comment by perhapszzy** [comment]
目前我们暂时没有提供1.2的代码，你可以换到1.0下试试

**Comment by chnhaoqiu** [comment]
好的，谢谢，无以为0.12文件中的代码是1.2版本的。。。
