### ISSUE TITLE
8.4.1章书中实例代码可能有问题

### ISSUE THREAD

**Issue by saselovejulie** [caicloud/tensorflow-tutorial#61]
8.4.1章中有一个转换向量形态的操作.
output = tf.reshape(tf.concat(outputs, 1), [-1, HIDDEN_SIZE])
这是正确的代码. 
但是书中写的是 
output = tf.reshape(tf.concat(1, outputs), [-1, HIDDEN_SIZE])
会导致代码报错. 如果我提出的是错误的, 麻烦指正.
感谢

**Comment by saselovejulie** [comment]
@perhapszzy @ScorpioCPH 
[第八章 使用循环神经网络实现语言模型](https://github.com/caicloud/tensorflow-tutorial/issues/28)
这个issue可能和我创建的这个是一个问题. 因为issue中的代码是书中的错误代码?

**Comment by ScorpioCPH** [comment]
@saselovejulie 是的，这个应该是个 bug，欢迎提 PR 来 fix 掉

**Comment by saselovejulie** [comment]
@ScorpioCPH 
可能是我描述的不清楚, Git上面的代码上是正确的. 但是书中印刷是错误的. 如果直接运行Git的代码没有问题.
书中Page219的output的代码是错误的.
谢谢

**Comment by perhapszzy** [comment]
书中代码是已0.9.0的API为基础，所以会不大一样。
