### ISSUE TITLE
第9章9.22 节点信息问题

### ISSUE THREAD

**Issue by yanyu003** [caicloud/tensorflow-tutorial#66]
train_writer.add_run_metadata(run_metadata,'step%03d',%i)

train_writer哪里定义了呢?

出错:
    train_writer.add_run_metadata(run_metadata,'step%03d',%i)
                                                          ^
SyntaxError: invalid syntax

**Comment by nowgood** [comment]
随书代码改过来了，就是将 `train_writer` 改为 `writer`
