### ISSUE TITLE
code in 1.0.0/chapter09/ 2. 改造后的mnist_train.ipynb can not be opened

### ISSUE THREAD

**Issue by cleverzh** [caicloud/tensorflow-tutorial#69]
The code of" 2. 改造后的mnist_train.ipynb" in 1.0.0 chapter09 can not be opened. Maybe there are something wrong.

**Comment by perhapszzy** [comment]
可能这个pr破坏了juypter的语法，我看看
https://github.com/caicloud/tensorflow-tutorial/commit/8605e58d7a599dab01b28ade049a172a3a254349

**Comment by perhapszzy** [comment]
fixed
