### ISSUE TITLE
2.2.1 使用Docker安装 出现问题

### ISSUE THREAD

**Issue by xspkwy** [caicloud/tensorflow-tutorial#74]
命令
`$ docker run -it -p 8888:8888 -p 6006:6006 \
 cargo.caicloud.io/tensorflow tensorflow:0.12.0`
在ubuntu14.04，Docker17.09.0-ce上运行报错：
“docker: invalid reference format.
See 'docker run --help'.”

修改’-p'为‘-P'以及前面加’sudo'后会提示：
”docker: Error response from daemon: pull access denied for 8888, repository does not exist or may require 'docker login'.
See 'docker run --help'.“
请问是什么问题？怎么解决？

**Comment by ElementsPhoenix** [comment]
真不好意思哈，目前还不了解是什么原因造成的


发件人: xspkwy [mailto:notifications@github.com]
发送时间: 2017年10月18日 0:21
收件人: caicloud/tensorflow-tutorial <tensorflow-tutorial@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [caicloud/tensorflow-tutorial] 2.2.1 使用Docker安装 出现问题 (#74)


命令
$ docker run -it -p 8888:8888 -p 6006:6006 \ cargo.caicloud.io/tensorflow tensorflow:0.12.0
在ubuntu14.04，Docker17.09.0-ce上运行报错：
“docker: invalid reference format.
See 'docker run --help'.”

修改’-p'为‘-P'以及前面加’sudo'后会提示：
”docker: Error response from daemon: pull access denied for 8888, repository does not exist or may require 'docker login'.
See 'docker run --help'.“
请问是什么问题？怎么解决？

**Comment by xspkwy** [comment]
访问cargo.caicloud.io/tensorflow，会弹出
![fireshot capture 1 - not found - https___cargo caicloud io_tensorflow](https://user-images.githubusercontent.com/20251362/32044855-4de8edee-ba71-11e7-897c-123118465106.png)
所以可能是服务器的问题？

**Comment by Jimexist** [comment]
@xspkwy 请先用 `cargo.caicloud.io/caicloud/tensorflow` 替代

**Comment by xspkwy** [comment]
@Jimexist Sorry to reply for so long! 
And it surely works! Thanks!
