### ISSUE TITLE
关于本书Tensorflow5.2.1节中的问题

### ISSUE THREAD

**Issue by guoxixi1982** [caicloud/tensorflow-tutorial#76]
书中4.4.3节讲述了滑动平均技术。书中99页中用到这个技术时有一段代码如下：

![1](https://user-images.githubusercontent.com/27565218/32474272-c4e89e2e-c3a6-11e7-93de-38ade93e34af.png)

感觉这段代码怪怪的，tf.control_dependecies这个是用来进行控制依赖的，本意应该是让 操作variables_averges_op开始执行时确保train_op这个操作已经执行完成。查了下control_dependecies的功能，感觉应该写成
                        with tf.control_dependencies([train_op]):
                                     sess.run(variables_averages_op)

才比较符合滑动平均的逻辑，对书中注释和代码中提到的tf.no_op和tf.group也感到很费解，能不能请老师给解释下啊，感觉滑动平均还是很重要的。

**Comment by perhapszzy** [comment]
其实control_dependecies和group的目的都是为了让这两个操作一起被运行，所以形式其实不是那么重要。

**Comment by guoxixi1982** [comment]
啊？怎么又是一起执行了啊，越看与糊涂了。

按照逻辑应该是先执行train_op，确保变量被BP算法更新后，再来执行variables_averges_op才对啊。



是不是我对tf.control_dependecies（）本身的功能理解有误啊，比如
写成tf.control_dependecies（a, b, c），是不是说先a 执行完毕，才能执行b,   b执行完才行执行c  ?

**Comment by perhapszzy** [comment]
一起执行这里我指的是“都会被运行”，而不是时间上一起运行。严格来说应该是先运行优化train_step，再运行活动平均才能保证滑动平均计算的准确性。但因为我们会运行非常多轮迭代，所以对于这样的顺序要求也就不严格了。

**Comment by guoxixi1982** [comment]
看了您的回复我更加糊涂了

**Comment by nowgood** [comment]
@guoxixi1982
