### ISSUE TITLE
6.5.2的tensorflow实现迁移学习出现代码问题，该怎么解决。

### ISSUE THREAD

**Issue by zhihao-chen** [caicloud/tensorflow-tutorial#78]
第六章6.5.2的tensorflow实现迁移学习出现了一个代码问题：empty range for randrange()。问题出在执行get_random_cached_bottlenecks函数里的label_index = random.randrange(n_classes)。我的代码完全是跟书上一样的。不知道怎么回事。

**Comment by Watminf** [comment]
Replace file_glob = os.path.join(INPUT_DATA,dir_name,'*.'+extension) creat_image_lists

**Comment by Watminf** [comment]
函数creat_image_lists中，把file_glob = os.path.join(INPUT_DATA,dir_name,'*.'+extension)改成file_glob = os.path.join(sub_dir, '*.' + extension)

**Comment by 1056861744** [comment]
我也出现了相同的问题，按照你的修改，问题并没有解决。坐等回答

**Comment by understand94** [comment]
你好请问一下，在转换数据的过程中，processed_data会变得很大，导致内存溢出，不知道该如何解决？我的内存是8G。

**Comment by kjdnl** [comment]
求解惑，在第二版的第6章的迁移学习代码(162～164）页，那个数据处理的程序有问题，在将原始的RGB图片整理成模型需要的输入数据格式npy的时候。随着运行时间的增加，处理速度越来越慢，最终造成内存不够。
跑程序一直报memeory error，请问怎么纠错？求解惑？您能发我下正确的代码吗? 我邮箱406803818@qq.com

**Comment by kjdnl** [comment]
> 解决了，是路径出现问题，最后结尾加上'/'
请问你具体是怎么解决的?具体是在哪个路径最后结尾加上'/'，是在楼上的基础上改的？还是在你原来的基础上改的？求说清
