### ISSUE TITLE
5.2.1书上96-100的源代怎么找不到，找到的都是改动很大的，求解

### ISSUE THREAD

**Issue by jiangpanxun** [caicloud/tensorflow-tutorial#80]

**Comment by jiangpanxun** [comment]
照着书上敲了一遍，有错误，去下载资料，资料里没找到

**Comment by perhapszzy** [comment]
这个代码库里提供了书上所有的代码，你可以在这个repo里找找

**Comment by jiangpanxun** [comment]
没有找到，https://github.com/caicloud/tensorflow-tutorial/tree/master/Deep_Learning_with_TensorFlow/0.12.0/Chapter05
在这里也很书上的代码出入很大，求解

**Comment by perhapszzy** [comment]
可以参考：
https://github.com/caicloud/tensorflow-tutorial/blob/master/Deep_Learning_with_TensorFlow/1.0.0/Chapter05/2.%20TensorFlow%E8%AE%AD%E7%BB%83%E7%A5%9E%E7%BB%8F%E7%BD%91%E7%BB%9C/1.%20%E5%85%A8%E6%A8%A1%E5%9E%8B.ipynb
