### ISSUE TITLE
关于多GPU并行和分布式并行的设想和疑问

### ISSUE THREAD

**Issue by Zzmc** [caicloud/tensorflow-tutorial#81]
是否可以实现多GPU实现和分布式并行的结合，即集群每个节点有多个GPU，每个节点的计算用多GPU代码实现，求得的参数再用分布式代码提交到参数服务器进行整合。因为我发现，每个task只管理1个GPU效率较低，是否可以实现一个task管理多个GPU？请问可以给点建议吗？是否有相关的资料可以参考？

**Comment by ElementsPhoenix** [comment]
我不太懂哈，请你问别人 ^_^

发件人: Zzmc [mailto:notifications@github.com]
发送时间: 2017年11月30日 17:31
收件人: caicloud/tensorflow-tutorial <tensorflow-tutorial@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [caicloud/tensorflow-tutorial] 关于多GPU并行和分布式并行的设想和疑问 (#81)


是否可以实现多GPU实现和分布式并行的结合，即集群每个节点有多个GPU，每个节点的计算用多GPU代码实现，求得的参数再用分布式代码提交到参数服务器进行整合。因为我发现，每个task只管理1个GPU效率较低，是否可以实现一个task管理多个GPU？请问可以给点建议吗？是否有相关的资料可以参考？

**Comment by perhapszzy** [comment]
每个节点使用多个GPU是可行的，具体可以参考tensorflow官方样例
